apiVersion: v1
kind: Service
metadata:
  name: myservice
  label:
    app:myspringboot
spec:
  selector:
    app: myspringboot
  type: LoadBalancer
  ports:
  - nodePort: 30030
    port: 80
    targetPort: 9099

